### PR TITLE
eth fix

### LINKED ISSUE #60: ETH is not able to be included with addToken function
If ETH is not include on initialization is not able to be included later cause in [this line](https://github.com/1Hive/token-request-app/blob/master/contracts/TokenRequest.sol#L98) we check that the address pass as parameter is contract and in case of passing the ZERO_ADDRESS this always fails

### PR DESCRIPTION
**Pull request by rperez89**
Fix on the background script to add ETH only if it's present on the contract.
Require isContract only if the address is different from ETH

closes #60

### CODE REVIEW

File: app/src/script.js [hunk 1]
```diff
@@ -83,12 +83,13 @@ function initializeState(state, tokenManagerContract, tokens, settings) {
...
-        symbol: 'ETH',
-        address: ETHER_TOKEN_FAKE_ADDRESS,
-      })
+      tokens.includes(ETHER_TOKEN_FAKE_ADDRESS) &&
+        acceptedTokens.unshift({
+          decimals: '18',
+          name: 'Ether',
+          symbol: 'ETH',
+          address: ETHER_TOKEN_FAKE_ADDRESS,
+        })
```
Comment (fabriziovigevani) [inline app/src/script.js:90]: We can use the `ETHER_DATA` from above like so: 

```
acceptedTokens.unshift({
   ...ETHER_DATA,
  address: ETHER_TOKEN_FAKE_ADDRESS,
})
```

**Review by fabriziovigevani — APPROVED** [review]

**Review by willjgriff — APPROVED** [review]
